### ISSUE TITLE
state command returns empty encoding

### ISSUE THREAD

**Issue by LievenPetersen** [ftsell/pixelflut#8]
when sending "state rgb64", I only receive "STATE RGB64 \n"

Looking through the code, as far as I can tell, the encoding should be in between ' ' and '\n' (src/net/framing/write.rs:72).

Since I receive the delimiter, I think the encoding may be empty.
Looking at the passing around of "SharedMultiEncodings", they are ultimately created as String::new(). So unless they are filled by some update function, they would indeed be empty strings.

**Comment by lilioid** [comment]
You're right in saying that the encoding starts out an empty string. It gets periodically updated in the background with the most recent encoding result from a task that is started in [`state_encoding/mod.rs:24`](https://github.com/ftsell/pixelflut/blob/main/rust/src/state_encoding/mod.rs#L24).
I deactivated that part during the OE because we didn't really need it and because I didn't want to maintain it during the changes I made in the last week 😅

**Comment by LievenPetersen** [comment]
Haha no worries^^
I ended up polling each pixel individually, which, compared to the war that was going on, was probably not too much traffic.
I was just unsure if this was intentional or not ;)
